[build]
  publish = "public"
  command = "echo 'No build required'"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9.12"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 