[build]
  base = "notary-dashboard"
  command = "npm install && npm run build"
  publish = "notary-dashboard/.next"
  functions = "netlify/functions"
  
# Disable Python and Ruby detection
[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_PYTHON = "false"
  NETLIFY_USE_RUBY = "false"
  NEXT_TELEMETRY_DISABLED = "1"
  
# The following redirect rule ensures that all paths are served by the index.html file,
# which is necessary for single-page applications with client-side routing
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 