[build]
  publish = "public"
  
# The following redirect rule ensures that all paths are served by the index.html file,
# which is necessary for single-page applications with client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 