[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"
  
# Disable Python and Ruby detection
[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_PYTHON = "false"
  NETLIFY_USE_RUBY = "false"
  NEXT_TELEMETRY_DISABLED = "1"
  
# The following redirect rule ensures that all paths are served by the index.html file,
# which is necessary for single-page applications with client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 