[build]
  publish = "public"
  command = ""
  
# Disable Python and Ruby detection
[build.environment]
  NETLIFY_USE_PYTHON = "false"
  NETLIFY_USE_RUBY = "false"
  RUBY_VERSION = "false"
  NODE_VERSION = "18"
  
# The following redirect rule ensures that all paths are served by the index.html file,
# which is necessary for single-page applications with client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 