services:
  - type: web
    name: notary-voice-admin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn admin_dashboard:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: AGENT_ID
        sync: false 